
* Key Management

* Server Keys

Longer lived keys
Erlang


* Client Side,


Info on browser crypto.

https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet

https://pomcor.com/2017/06/02/keys-in-browser/
https://www.w3.org/TR/WebCryptoAPI/
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
https://www.w3.org/TR/IndexedDB/
https://www.boxcryptor.com/en/blog/post/building-an-app-with-webcrypto-in-2016/
https://gist.github.com/saulshanabrook/b74984677bccd08b028b30d9968623f5
https://blog.engelke.com/2014/09/19/saving-cryptographic-keys-in-the-browser/

** Questions

*** Where to store keys and attributes.

- sessionStorage, per tab/site storage. When the tab closes, the data is gone.
- localStorage, per site storage. Data is shared between tabs, and stored on the computer.
- indexDB, indexed storage of items, queryable. (but partial support in IE11)

  
*** What parts of indexDB is not supported by IE11?

There is a shim. https://github.com/axemclion/IndexedDBShim

*** What happens with the sessionStorage?

- Is it deleted? Was it stored on disk or just memory.


*** How fast is key generation?

On my iMac (i5, 3.3 Ghz) generating a 2048 bit RSA key costs, 200ish
microseconds. A 1024 bit key 30-ish.

Also interesting, it is possible to create a key-pair in such a way
that it is not possible to extract the key so you can re-use the key
later. This sounds like an interesting way to generate temporary keys.

#+NAME: key-generation
#+BEGIN_SRC js
let promise = crypto.subtle.generateKey(
    {
        name: "RSA-OAEP",
        modulusLength: 1024,
        publicExponent: new Uint8Array([1, 0, 1]),  // 24 bit representation of 65537
            hash: {name: "SHA-256"}
        },
        false,   // <-- can extract private part later.
        ["encrypt", "decrypt"]
)
#+END_SRC

*** Short lived?



*** Regenerate often? 

*** How to authenticate server keys?

** Papers

*** Resurrecting Duckling

https://www.cl.cam.ac.uk/~fms27/papers/1999-StajanoAnd-duckling.pdf

*** Key Continuity Management

https://simson.net/thesis/pki3.pdf

This is SSH's model.

Under normal operation SSH alerts the *first* time that a new service is
contacted. After that first contact, however, SSH is silent unless
the server’s key changes.

*** Overview by NIST

http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-130.pdf

*** Ceremony Design and Analysis

https://eprint.iacr.org/2007/399.pdf
